feature: restore from devtools repository

diff --git a/bin/git-delete b/bin/git-delete
--- a/bin/git-delete
+++ b/bin/git-delete
@@ -14,20 +14,17 @@
 # work that is not merged elsewhere. Upstream branches are not deleted.
 # ==============================================================================
 
-# Absolute path to this script, e.g. `/path/to/dotfiles/bin/foo.sh`.
-#
-# TODO: `readlink` is not a POSIX utility, so need to find a better cross-
-# platform way of achieving this.
+# Absolute path to this script, eg `/path/to/dotfiles/bin/foo.sh`.
 FILE_PATH=$(readlink -f "$0")
 
-# Absolute path to this script's parent directory, thus `/path/to/dotfiles/bin`.
+# Absolute path to the bin directory, thus `/path/to/dotfiles/bin`.
 BIN_PATH=$(dirname "$FILE_PATH")
 
 # Absolute path this repo, thus `/path/to/dotfiles`.
 REPO_PATH=$(dirname "$BIN_PATH")
 
 # Source ANSI code variables.
-source "${REPO_PATH}/lib/ansi-codes.sh"
+. "${REPO_PATH}/lib/ansi-codes.sh"
 
 # Was the target branch provided as a parameter?
 branch="${1}"
@@ -35,29 +32,35 @@ branch="${1}"
 # If not, let the user select from a list.
 if [ -z "${branch}" ]; then
 
-  branches=()
-  eval "$(git for-each-ref --sort='-authordate:iso8601' --shell --format='branches+=(%(refname))' refs/heads/)"
+  branches=$(git for-each-ref --sort='-authordate:iso8601' --format='%(refname)' refs/heads/)
 
   # TODO:
   # Remove main, master and current branch from list of available branches to delete.
 
-  length=${#branches[@]}
-  for (( i=0; i<${length}; i++ ))
+  set -- "${branches}"
+  i=0
+  for branch_name
   do
-    branch_name="${branches[$i]}"
-
     # Remove refs/heads/ from start of branch name
-    echo -e "${YELLOW}${i}${RESET} - ${branch_name:11}"
+    branch_name=$(echo "$branch_name" | sed 's|refs/heads/||')
+    printf "%b${i}%b - ${branch_name}" "${YELLOW}" "${RESET}"
+    i=$((i + 1))
   done
 
   echo ""
-  echo -e "${BLUE}Type the number of the branch you want to delete:${RESET}"
+  printf "%bType the number of the branch you want to delete:%b" "${BLUE}" "${RESET}"
 
-  read -p "> " index
+  # Bash-compatible code:
+  #read -p "> " index
+
+  # Posix-compatible code:
+  printf "> " >&2
+  read -r index
+
   echo ""
 
   if [ -z "${index}" ]; then
-    echo -e "${RED}Branch not provided, exiting...${RESET}" >&2
+    printf "%b%b Branch not provided, exiting. %b" "${RED}" "${REVERSED}" "${RESET}" >&2
     exit 1
   fi
 
@@ -66,39 +69,45 @@ if [ -z "${branch}" ]; then
 
 fi
 
-echo -e "${GREEN}Attempting deletion of ${REVERSED} ${branch} ${RESET}"
+printf "%bAttempting deletion of %b ${branch} %b" "${GREEN}" "${REVERSED}" "${RESET}"
 
 # Attempt to delete the local branch. Silence non-error output and capture
 # errors. Respond to errors by asking the user if they want to try a force-delete.
-git branch --quiet --delete ${branch} 2> /dev/null
+git branch --quiet --delete "${branch}" 2> /dev/null
 EXIT_CODE_1=$?
 
 if [ ${EXIT_CODE_1} -eq 1 ]; then
 
   echo ""
-  echo -e "${RED}Branch deletion failed.${RESET}"
+  printf "%bBranch deletion failed.%b" "${RED}" "${RESET}"
   echo "Would you like to force deletion of this branch?"
   echo "WARNING: This is a destructive operation. This risks permanently losing commits that don't exist in the history of any other local branch."
-  read -p "Force delete? (y/n) " choice
+
+  # Bash-compatible code:
+  #read -p "Force delete? (y/n) " choice
+
+  # Posix-compatible code:
+  printf "Force delete? (y/n) " >&2
+  read -r choice
 
   case "$choice" in
     y|Y )
       # Hide all errors from these commands. Basically, if these fail, the
       # branch almost certainly does not exist or is somehow protected from
       # deletion (for example, it is the current checked out branch).
-      git branch --quiet --delete --force ${branch} 2> /dev/null
-      echo -e "${GREEN}Done.${RESET}"
+      git branch --quiet --delete --force "${branch}" 2> /dev/null
+      printf "%bDone.%b" "${GREEN}" "${RESET}"
       ;;
 
     n|N )
-      echo -e "${RED}Exiting...${RESET}"
+      printf "%bExiting...%b" "${RED}" "${RESET}"
       ;;
 
     * )
-      echo -e "${RED}Exiting...${RESET}"
+      printf "%bExiting...%b" "${RED}" "${RESET}"
       ;;
   esac
 
-else 
-  echo -e "${GREEN}Done.${RESET}"
+else
+  printf "%bDone.%b" "${GREEN}" "${RESET}"
 fi
